config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'movies#index'

  resources :movies
  resources :questions
  resources :aws_texts
  resources :lines
  resources :texts
  resources :questions, only: [:index, :show, :create, :edit, :update] do
    resource :solutions, only: [:create]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aws_text.rb
class AwsText < ApplicationRecord
end

app/models/line.rb
class Line < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord

end

app/models/question.rb
class Question < ApplicationRecord
  has_many :solutions
  validates :title, presence: { message: "【質問】は空欄にできません" }
  validates :detail, presence: { message: "【詳細】は空欄にできません" }

  def self.build_and_count_up(id)
    question = Question.find(id)
    question.record_timestamps = false
    question.count += 1
    question.save!
    question.record_timestamps = true

    question
  end
end
#　bk
#class Question < ApplicationRecord
#  has_many :solutions
#  validates :title, presence: true
#  validates :detail, presence: true
#end

app/models/solution.rb
class Solution < ApplicationRecord
  belongs_to :question
  validates :content, presence: { message: "【回答】は空欄にできません" }
end

#bk
# class Solution < ApplicationRecord
#   belongs_to :question
# end

app/models/text.rb
class Text < ApplicationRecord
  validates :genre, presence: true
  validates :title, presence: true
  validates :detail, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/aws_texts_controller.rb
class AwsTextsController < ApplicationController

before_action :authenticate_user!

def index
  @awstexts = AwsText.all.order(id: "ASC")
end

def show
  @awstext = AwsText.find(params[:id])
end

end

app/controllers/lines_controller.rb
class LinesController < ApplicationController

before_action :authenticate_user!

def index
  @lines = Line.all.order(id: "ASC")
end

def show
  @line = Line.find(params[:id])
end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

before_action :authenticate_user!

  def index
    @movies = Movie.where(genre: (params[:genre] || "movie")).order(id: "ASC").page(params[:page]).per(10)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

before_action :authenticate_user!
before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @questions = Question.all.order("created_at DESC")
    @question = Question.new

  end

  def show
    @question = Question.find(params[:id])
    @solutions = Solution.where(question_id: @question.id)
    @solution = @question.solutions.new
  end

  def create
    @question = Question.new(question_params)

    # インスタンスの保存に成功した場合
    if @question.save
      flash[:notice] = "質問を投稿しました。"
      redirect_to questions_path

    # インスタンスの保存に失敗した場合
    else
      flash.now[:danger] = "質問の登録に失敗しました。"
      @questions = Question.all.order(id: "DESC")
      render :index
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :detail)
  end

end

#bk
#class QuestionsController < ApplicationController

#before_action :authenticate_user!
#before_action :ensure_correct_user, only: [:edit, :update]
#  def index
#   @questions = Question.all.order(id: "DESC")
#    @question = Question.new
#  end

#  def show
#    @question = Question.find(params[:id])
#    @solutions = Solution.where(question_id: @question.id)
#  end

#  def create
#    @question = Question.new(question_params)

    # インスタンスの保存に成功した場合
#    if @question.save
#      flash[:notice] = "質問を投稿しました。"
#      redirect_to questions_path

    # インスタンスの保存に失敗した場合
#    else
#      flash.now[:danger] = "質問の登録に失敗しました。"
#      @questions = Question.all.order(id: "DESC")
#      render :index
#    end
#  end

#  private

#  def question_params
#    params.require(:question).permit(:title, :detail)
#  end

#end

app/controllers/solutions_controller.rb
#回答コントローラー
class SolutionsController < ApplicationController
  before_action :authenticate_user!

  def create
    @question = Question.find(params[:question_id])
    @solution = @question.solutions.build(solution_params)
    if @solution.save
      flash[:success] = "回答を投稿しました。"
      redirect_to question_path(@question.id)
    else
      @solutions = Solution.where(question_id: @question.id)
      render "questions/show", question_id: @question.id
    end
  end

  private

    def solution_params
      params.require(:solution).permit(:content)
    end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController

before_action :authenticate_user!

  def index
    @texts = Text.all
  end

  def show
    @text = Text.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithCoderay < Redcarpet::Render::HTML
    def block_code(code, language)
      case language.to_s
      when 'rb'
        lang = 'ruby'
      when 'yml'
        lang = 'yaml'
      when ''
        # 空欄のままだと「Invalid id given:」エラー
        lang = 'md'
      else
        lang = language
      end

      CodeRay.scan(code, lang).div
    end
  end

  def markdown(text)
    html_render = HTMLwithCoderay.new(filter_html: true, hard_wrap: true)
    options = {
      autolink: true,
      space_after_headers: true,
      fenced_code_blocks: true,
    }
    markdown    = Redcarpet::Markdown.new(html_render, options)
    markdown.render(text)
  end

  def bg_color
    controller_name == "lines" ? "bg-success" : "bg-danger"
  end

  def text_color
    controller_name == "lines" ? "text-success" : "text-danger"
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/views/aws_texts/index.html.erb
<table class="base-container table">
<center><h2 class="listtitle">AWS講座</h2></center>
<p class="awscaution">注意！！！：AWSのEC2やRDSは有料サービスとなります。無駄な料金を請求されないためにも、不要なインスタンスは停止・削除をしてください。</p>
<tr class="list-group-item-primary bg-primary"><th>No.</th><th>内容</th></tr>
<% @awstexts.each.with_index(1) do |awstext, i| %>
<tr class="listindex">
  <td><%= i %></td>
  <td><%= link_to( aws_text_path(awstext), target: :_blank) do %><%= awstext.title %><% end %></td></tr>
<% end %>
</table>

app/views/aws_texts/show.html.erb
<div class="base-container listcontent">
<%= markdown(@awstext.content).html_safe %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <title>GyakutenCloneGroup10</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/footer' %>

    <div class="base-container">
    <%= yield %>
    </div>
    
  </body>
</html>

app/views/lines/index.html.erb
<table class="base-container table">
<center><h2 class="listtitle text-success">LINE@</h2></center>
<tr class="list-group-item-primary bg-success"><th>No.</th><th>ジャンル</th><th>内容</th></tr>
<% @lines.each.with_index(1) do |line, i| %>
<tr class="listindex">
  <td><%= i %></td>
  <td><%= line.genre %>
  <td><%= link_to( line_path(line), target: :_blank) do %><%= line.title %><% end %></td></tr>
<% end %>
</table>

app/views/lines/show.html.erb
<div class="line-container">
  <%= markdown(@line.content).html_safe %>
</div>

app/views/movies/index.html.erb
<%= render 'shared/flash_messages' %>
<div class="base-container">
  <% @movies.each do |movie| %>
    <div class="youtube-title"><%= movie.title %></div>
    <% iframe = content_tag(
      :iframe,
      '', # empty body
      width: 560,
      height: 315,
      src: movie.url,
      frameborder: 0,
      allowfullscreen: true
      ) %>
    <%= content_tag(:div, iframe, class: 'youtube-container') %>
  <% end %>
<%= paginate @movies %>
</div>

app/views/questions/_form.html.erb
<%= form_with(model: @question, local: true) do |question| %>
  <div class="form_group pt-4 pb-3">
    <p>【質問】</p>
    <%= question.text_area :title, class: "form-question" %>
  </div>

  <div class="form-group" >
    <p>【詳細】</p>
    <%= question.text_area :detail, class: "form-detail" %>
  </div>

  <div class="text-center">
    <!--送信ボタンの横幅変更-->
    <%= question.submit "送信", class: "btn btn-primary btn-lg btn-block", data: {confirm: '新規投稿しますか？'} %>
  </div>
<% end %>

app/views/questions/_solution_form.html.erb
<div>
  <h1>回答投稿</h1>
  <%= form_with model: [@question, @solution], local: true do |f| %>
    <div class="form-group">
      <%= f.label :content, "【回答】", class: 'control-label' %>
      <%= f.text_area :content,
                      class: "form-control initial-height
                            #{'is-invalid' if @solution.errors.full_messages_for(:content).any?}",
                      rows: 5 %>
    </div>
    <div class="form-group">
      <%= f.submit "送信", class: "btn btn-primary btn-block btn-lg", data: {confirm: "投稿しますか？"} %>
    </div>
  <% end %>
</div>

app/views/questions/index.html.erb
<!--base code-->

  <div class="base-container">
  <%= render 'shared/flash' %>

  <div>
    <h2 class="text-left pt-5">新規投稿</h2>
    <%= render 'questions/form' %>
  </div>

  <% @questions.each do |question| %>
    <%= link_to( question_path(question), class: 'list-question') do %>
    <div class="question">
      <%= question.title.truncate(30) %><br>
      <%= question.detail.truncate(20) %><br>
    </div>
    <% end %>
  <% end %>
</div>

app/views/questions/show.html.erb
<%= render 'shared/questionshow' %>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: ["#{key}","flash"]) %>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name %>" role="alert" id="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer fixed-bottom <%= bg_color %> ">
  <a class="ftext" href="https://utina.yoshitokamizato.com/" target="_blank">ブログ</a>
  <a class="ftext" href="https://www.youtube.com/channel/UCwrDvYey9uKGBeh_l5IF-ag" target="_blank">Youtube</a>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark sticky-top <%= bg_color %>" style="background-color: #c22a1f">
  <a class="navbar-brand" href="#">Gyakuten</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle" href="/movies?genre=movie" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Rails
        </a>
        <div class="dropdown-menu " aria-labelledby="navbarDropdown">
          <a class="nav-item nav-link active select <%= text_color %>" href="/movies?genre=movie">動画教材</a>
          <a class="nav-item nav-link active select <%= text_color %>" href="/texts">テキスト教材</a>
          <a class="nav-item nav-link active select <%= text_color %>" href="/movies?genre=live">ライブコーディング</a>
          <a class="nav-item nav-link active select <%= text_color %>" href="/questions">質問集</a>
        </div>
      </li>

      <li class="nav-item active">
        <a class="nav-link" href="/aws_texts">AWS講座</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/movies?genre=php">PHP講座</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/movies?genre=talk">対談</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/movies?genre=marketing">情報発信</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/movies?genre=edit">動画編集講座</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/movies?genre=writing">ライティング講座</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/lines">LINE@</a>
      </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to "ログイン", new_user_session_path, class: 'post', :style=>"color:white;", class: "nav-link" %>
          </li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_questionshow.html.erb
<div class="container">
  <section>
  <div class="title">
    <h3>【質問】</h3>
    <p><%= @question.title %></p>
  </div>
  <hr>
  <div class="detail">
    <h3>【詳細】</h3>
    <p><%= markdown(@question.detail).html_safe %></p>
  </div>
  <% if @solutions.present? %>
    <% @solutions.each.with_index(1) do |solution, index| %>
      <!-- 回答が１つしかない場合は，【回答1】でなく【回答】と表示するためにindexをnilに変更-->
      <% index = nil if @solutions.length == 1 %>
      <hr>
      <div class="solution">
        <h3>【回答<%= index %>】</h3>
        <p><%= markdown(solution.content).html_safe %></p>
      </div>
    <% end %>
  <% end %>
</section>
<%= render 'questions/solution_form' %>

app/views/texts/index.html.erb
<div class="text-container">
  <h2><center>テキスト教材</center></h2>
  <% @texts.each.with_index(1) do |text, i| %>
    <%= link_to( text_path(text), target: :brank) do %>
    <div class="text">
      <%= image_tag "image#{format("%02d", i)}.png", class: "image" %><br>
      <div class="textmargin">
        <%= text.title %><br>
        【<%= text.genre %>】<br>
      </div>
    </div>
    <% end %>
  <% end %>
</div>

app/views/texts/show.html.erb
<div class="textdetail-container">
  <% text = @text.detail %>
  <%= markdown(text).html_safe %>
  <a href="https://twitter.com/share?url=<%= request.url %>&text=<%= @text.title %>" rel="nofollow" target="_blank"><%= image_tag "Twitter_Social_Icon_Square_Color.png", class: "icon" %></a>
  <a href="https://www.facebook.com/share.php?url=<%= request.url %>&text=<%= @text.title %>" rel="nofollow" target="_blank"><%= image_tag "f_logo_RGB-Blue_58.png", class: "icon" %></a>
</div>